"""Independent no-import audit of the five-mode row-pair theorem."""


def neighbourhoods(pattern):
    return tuple(
        frozenset(index for index, label in enumerate(pattern) if color in label)
        for color in range(3)
    )


def matrix_multiply(left, right):
    return [
        [sum(left[row][inner] * right[inner][column] for inner in range(len(right)))
         for column in range(len(right[0]))]
        for row in range(len(left))
    ]


def transpose(matrix):
    return [list(column) for column in zip(*matrix)]


def determinant_3(matrix):
    return (
        matrix[0][0] * (matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1])
        - matrix[0][1] * (matrix[1][0] * matrix[2][2] - matrix[1][2] * matrix[2][0])
        + matrix[0][2] * (matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0])
    )


def rank_3(matrix):
    if determinant_3(matrix):
        return 3
    for first_row in range(3):
        for second_row in range(first_row + 1, 3):
            for first_column in range(3):
                for second_column in range(first_column + 1, 3):
                    minor = (
                        matrix[first_row][first_column] * matrix[second_row][second_column]
                        - matrix[first_row][second_column] * matrix[second_row][first_column]
                    )
                    if minor:
                        return 2
    return 1 if any(value for row in matrix for value in row) else 0


def main():
    # Canonical types derived from the integer partitions in the proof; this
    # list is not generated by a support or mode-assignment search.
    patterns = {
        "I": ((1, 2), (1, 2), (0,), (0,)),
        "II": ((1, 2), (0, 2), (0,), (1,)),
        "III": ((1, 2), (0, 2), (0, 1), (0,)),
        "IV": ((1, 2), (1, 2), (0, 2), (0,)),
        "V": ((1, 2), (1, 2), (0, 2), (0, 2)),
        "VI": ((1, 2), (1, 2), (0, 2), (0, 1)),
    }
    expected = {
        "I": (2, 2, 2),
        "II": (2, 2, 2),
        "III": (3, 2, 2),
        "IV": (2, 2, 3),
        "V": (2, 2, 4),
        "VI": (2, 3, 3),
    }
    witnesses = {"II": 2, "III": 1, "IV": 1, "V": 0, "VI": 0}

    for name, raw_pattern in patterns.items():
        pattern = tuple(frozenset(label) for label in raw_pattern)
        ns = neighbourhoods(pattern)
        assert tuple(map(len, ns)) == expected[name]
        if name in witnesses:
            color = witnesses[name]
            pair = ns[color]
            assert len(pair) == 2
            assert all(ns[other] != pair for other in range(3) if other != color)
            assert all(len(pattern[index]) == 2 for index in pair)

    # Exact integer port calculation for two {1,2} coordinate planes.
    j_form = [[0, 1], [1, 0]]
    r_left = [[0, 1, 0], [0, 0, 1]]
    r_right = [[0, 0, 1], [0, 1, 0]]
    port = matrix_multiply(matrix_multiply(transpose(r_left), j_form), r_right)
    assert port == [[0, 0, 0], [0, 1, 0], [0, 0, 1]]
    assert rank_3(port) == 2

    # Type I second slice: e1 in the collapsed singleton kernel kills target
    # colours zero and two, while a nonzero colour-one shore keeps colour one.
    collapsed_vector = (0, 1, 0)
    other_vectors = ((0, 2, 3), (4, 5, 6), (7, 8, 9))
    target_diagonal = tuple(
        collapsed_vector[color]
        * product(vector[color] for vector in other_vectors)
        for color in range(3)
    )
    assert target_diagonal == (0, 80, 0)
    target_matrix = [
        [target_diagonal[0], 0, 0],
        [0, target_diagonal[1], 0],
        [0, 0, target_diagonal[2]],
    ]
    assert rank_3(target_matrix) == 1

    print("PASS: independent six-type incidence audit")
    print("PASS: corrected Y=3 repeated-doubleton type included")
    print("PASS: exact integer rank-two port versus rank-one polar targets")
    print("SCOPE: arbitrary-order five-mode lower bound; global problem unresolved")


def product(values):
    result = 1
    for value in values:
        result *= value
    return result


if __name__ == "__main__":
    main()
