#!/usr/bin/env python3
"""Verify the common-singleton pure-P4 component and its local height certificate."""

from __future__ import annotations

import contextlib
import hashlib
import io
import json
import shutil
import subprocess
from pathlib import Path

import analyze_p4_common_singleton_local_dimension as analysis

ROOT = Path(__file__).resolve().parent
THEOREM = ROOT / "P4_COMMON_SINGLETON_COMPONENT.md"
GRAPH_SLICE = ROOT / "tmp" / "p4_common_singleton_local_graph_slice.sing"
PRIME = 32003
EXPECTED_GRAPH_SLICE_SHA256 = (
    "4aaf80d0f2e08550e7f2929cb0eda9443b79ce8a0945f5cc8113a48a5d5c0b7b"
)
EXPECTED_STANDARD_BASIS_SIZE = 36
EXPECTED_LOCAL_DIMENSION = 0
EXPECTED_VECTOR_SPACE_DIMENSION = 56

# Ordered as (01,02,03,12,13,23).  These exact profiles are asserted in the
# existing component verifiers listed below.  A rank-four entry is enough to
# separate each old component closure from the closed all-pair-rank<=3 locus.
KNOWN_COMPONENT_PROFILES = {
    "1": (4, 4, 4, 3, 3, 3),
    "2-5": (4, 4, 3, 4, 3, 3),
    "6": (4, 4, 3, 4, 3, 3),
    "7": (4, 3, 2, 4, 4, 3),
    "8": (4, 4, 3, 4, 3, 3),
    "9": (4, 4, 4, 2, 2, 2),
    "10": (3, 3, 3, 4, 4, 4),
    "11": (4, 4, 4, 3, 3, 3),
    "12": (3, 3, 4, 3, 3, 3),
    "13": (4, 4, 4, 3, 3, 3),
    "14": (2, 3, 4, 3, 4, 4),
    "15": (2, 3, 4, 3, 4, 4),
    "16-17": (4, 4, 4, 3, 3, 3),
}

PROFILE_SOURCE_FRAGMENTS = {
    "verify_p4_diagonal_quadric_one_three_components.py": (
        'profiles["known_first"] == (4, 4, 4, 3, 3, 3)',
        'profiles[name] == (4, 4, 3, 4, 3, 3)',
    ),
    "verify_p4_mixed_orientation_pure_component.py": (
        '"pair_profile": [4, 4, 3, 4, 3, 3]',
    ),
    "verify_p4_six_dimensional_pure_component.py": (
        "pair_profile == (4, 3, 2, 4, 4, 3)",
    ),
    "verify_p4_disjoint_mixed_star_pure_component.py": (
        "pair_profile == (4, 4, 3, 4, 3, 3)",
    ),
    "verify_p4_embedded_p3_pure_component.py": (
        "profile == (4, 4, 4, 2, 2, 2)",
    ),
    "verify_p4_two_rank_two_spoke_mixed_star_component.py": (
        '"pair_profile": [3, 3, 3, 4, 4, 4]',
    ),
    "verify_p4_equal_support_common_factor_component.py": (
        '"pair_profile": [4, 4, 4, 3, 3, 3]',
    ),
    "verify_p4_transverse_common_factor_component.py": (
        "pair_profile == [3, 3, 4, 3, 3, 3]",
    ),
    "verify_p4_eisenstein_norm_common_kernel_component.py": (
        "pair_profile == [4, 4, 4, 3, 3, 3]",
    ),
    "verify_p4_full_support_tangent_pair_component.py": (
        "pair_profile == [2, 3, 4, 3, 4, 4]",
    ),
    "verify_p4_disjoint_secant_lower_pair_component.py": (
        "pair_profile == [2, 3, 4, 3, 4, 4]",
    ),
    "verify_p4_directed_zero_divisor_triangle_components.py": (
        "profile == (4, 4, 4, 3, 3, 3)",
    ),
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def singular_command() -> list[str]:
    native = shutil.which("Singular")
    if native:
        return [native, "-q"]
    wsl = shutil.which("wsl.exe")
    if wsl:
        return [wsl, "--exec", "/usr/bin/Singular", "-q"]
    raise RuntimeError("Singular is required for the exact local replay")


def regenerate_graph_slice() -> str:
    captured = io.StringIO()
    with contextlib.redirect_stdout(captured):
        analysis.main()
    diagnostics = captured.getvalue()
    for expected in (
        "incidence_equations=15",
        "family_tangent_rank=5",
        "family_tangent_minor=1",
        "jacobian_rank=10",
        "active_transverse_columns=(12, 13, 17, 18, 19)",
        "pivot_determinant=-36864",
        "graph_slice_cleared_denominators=(96, 192, 2, 4, 48, 4, 6, 48, 64, 4, 1, 1, 1, 1, 1)",
        "graph_slice_cleared_contents=(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)",
        "graph_slice_family_restriction_determinant=1/4",
    ):
        assert expected in diagnostics
    assert GRAPH_SLICE.exists()
    assert sha256(GRAPH_SLICE) == EXPECTED_GRAPH_SLICE_SHA256
    source = GRAPH_SLICE.read_text(encoding="utf-8")
    assert source.startswith("// Generated by analyze_p4_common_singleton_local_dimension.py\n")
    assert "ring R=0,(y0,y1,y2,y3,y4,y5,y6,y7,y8,y9,y13,y14,y17,y18,y19),ds;" in source
    ideal_body = source.split("ideal I=\n  ", 1)[1].split(";\nint t=timer;", 1)[0]
    assert len(ideal_body.split(",\n  ")) == 15
    return source


def replay_local_standard_basis(source: str) -> dict[str, int]:
    modular_source = source.replace("ring R=0,", f"ring R={PRIME},", 1)
    modular_source += (
        '\nprint("CODEX_RESULT:"+string(size(G))+":"+string(dim(G))'
        '+":"+string(vdim(G)));\n'
    )
    completed = subprocess.run(
        singular_command(),
        input=modular_source,
        text=True,
        capture_output=True,
        timeout=600,
        check=False,
    )
    if completed.returncode != 0 or completed.stderr.strip():
        raise AssertionError(
            "Singular failed: "
            f"rc={completed.returncode}, stderr={completed.stderr!r}"
        )
    if "?" in completed.stdout:
        raise AssertionError(f"Singular reported an error:\n{completed.stdout}")
    prefix = "CODEX_RESULT:"
    markers = [
        line.strip()
        for line in completed.stdout.splitlines()
        if line.strip().startswith(prefix)
    ]
    assert len(markers) == 1, completed.stdout
    basis_size, local_dimension, vector_space_dimension = (
        int(value) for value in markers[0][len(prefix) :].split(":")
    )
    assert basis_size == EXPECTED_STANDARD_BASIS_SIZE
    assert local_dimension == EXPECTED_LOCAL_DIMENSION
    assert vector_space_dimension == EXPECTED_VECTOR_SPACE_DIMENSION
    return {
        "prime": PRIME,
        "standard_basis_size": basis_size,
        "special_fibre_local_dimension": local_dimension,
        "special_fibre_vector_space_dimension": vector_space_dimension,
    }


def _fragment_source_path(filename: str) -> Path:
    """Resolve a fragment-source script to its current location.

    The inventory scans the *text* of other verifiers (it never imports
    them).  Several of those verifiers are claim packages that the layout
    migration has moved out of the root, so a bare ``ROOT / filename``
    lookup goes stale.  This resolver first tries the root, then consults
    the executed-move map in ``catalog/moved-paths.json`` so it keeps
    finding each source at its post-migration path.
    """
    direct = ROOT / filename
    if direct.exists():
        return direct
    manifest_path = ROOT / "catalog" / "moved-paths.json"
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        for move in manifest.get("moves", []):
            if move.get("status") == "moved" and move.get("old_path") == filename:
                candidate = ROOT / move["new_path"]
                if candidate.exists():
                    return candidate
    return direct


def verify_known_component_inventory() -> dict[str, list[int]]:
    for filename, fragments in PROFILE_SOURCE_FRAGMENTS.items():
        text = _fragment_source_path(filename).read_text(encoding="utf-8")
        for fragment in fragments:
            assert fragment in text, (filename, fragment)
    assert all(max(profile) == 4 for profile in KNOWN_COMPONENT_PROFILES.values())
    return {
        component: list(profile)
        for component, profile in KNOWN_COMPONENT_PROFILES.items()
    }


def main() -> None:
    graph_source = regenerate_graph_slice()
    local_certificate = replay_local_standard_basis(graph_source)
    known_profiles = verify_known_component_inventory()

    output = {
        "verified": True,
        "field": "C",
        "method": (
            "exact family identities and Jacobians; an integral graph slice; "
            "an exact local standard basis over F_32003; and Krull height "
            "lifting to characteristic zero"
        ),
        "family_parameters": 5,
        "family_tangent_rank": 5,
        "sample_anchor_coefficient": 4,
        "sample_pair_profile": [3, 3, 3, 3, 3, 3],
        "sample_pair_relation_matrix_ranks": [1, 1, 1, 1, 1, 1],
        "universal_incidence_variables": 20,
        "universal_incidence_equations": 15,
        "universal_incidence_jacobian_rank": 10,
        "graph_slice_variables": 15,
        "graph_slice_equations": 15,
        "graph_slice_sha256": EXPECTED_GRAPH_SLICE_SHA256,
        "graph_slice_pivot_determinant": -36864,
        "graph_slice_cleared_denominators": [
            96,
            192,
            2,
            4,
            48,
            4,
            6,
            48,
            64,
            4,
            1,
            1,
            1,
            1,
            1,
        ],
        "graph_slice_cleared_contents": [1] * 15,
        "graph_slice_family_restriction_determinant": "1/4",
        **local_certificate,
        "integral_slice_height": 15,
        "characteristic_zero_slice_local_dimension": 0,
        "universal_incidence_local_dimension": 5,
        "irreducible_component_certified": True,
        "closed_separating_condition": "all six pair-product ranks <= 3",
        "known_component_profiles": known_profiles,
        "new_component_orbit_number": 18,
        "all_pure_components_classified": False,
        "generic_P5_fibres_excluded_by_this_theorem": False,
        "generic_P5_companion_theorems": [
            "P5_H31_COMMON_SINGLETON_COMPONENT_GENERIC_OBSTRUCTION.md",
            "P5_H22_COMMON_SINGLETON_COMPONENT_GENERIC_OBSTRUCTION.md",
        ],
        "global_conjecture_resolved": False,
        "theorem": THEOREM.name,
        "theorem_sha256": sha256(THEOREM),
        "source": Path(__file__).name,
        "source_sha256": sha256(Path(__file__)),
    }
    output_path = ROOT / "tmp" / "p4_common_singleton_component_verified.json"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(output, indent=2))


if __name__ == "__main__":
    main()
