#!/usr/bin/env python3
"""Verify the common-active binary triangle component and integral height slice."""

from __future__ import annotations

import contextlib
import hashlib
import io
import json
import shutil
import subprocess
from pathlib import Path

import analyze_p4_common_active_binary_triangle_local_dimension as analysis

ROOT = Path(__file__).resolve().parent
GRAPH_SLICE = ROOT / "tmp" / "p4_common_active_binary_local_graph_slice.sing"
PRIME = 101
EXPECTED_GRAPH_SLICE_SHA256 = (
    "346598947e89b7d088b016bbe559942e56d8791fe3879b388d6bb38b922f594d"
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def singular_command() -> list[str]:
    native = shutil.which("Singular")
    if native:
        return [native, "-q"]
    if shutil.which("wsl.exe"):
        return ["wsl.exe", "--exec", "/usr/bin/Singular", "-q"]
    raise RuntimeError("Singular is required for the exact local replay")


def regenerate_graph_slice() -> str:
    captured = io.StringIO()
    with contextlib.redirect_stdout(captured):
        analysis.main()
    diagnostics = captured.getvalue()
    for expected in (
        "family_tangent_rank=5",
        "family_tangent_minor=-1/6",
        "sample_pair_profile=(4, 4, 4, 3, 3, 3)",
        "incidence_jacobian_rank=12",
        "fixed_coordinates=(0, 1, 2, 3, 6)",
        "retained_indices=(4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)",
        "slice_denominators=(6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6)",
        "slice_contents=(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)",
    ):
        assert expected in diagnostics
    assert GRAPH_SLICE.exists()
    source = GRAPH_SLICE.read_text(encoding="utf-8")
    assert source.startswith(
        "// Generated by analyze_p4_common_active_binary_triangle_local_dimension.py\n"
    )
    assert "ring R=0,(x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14),ds;" in source
    ideal_body = source.split("ideal I=\n  ", 1)[1].split(";\nint t=timer;", 1)[0]
    assert len(ideal_body.split(",\n  ")) == 15
    assert sha256(GRAPH_SLICE) == EXPECTED_GRAPH_SLICE_SHA256
    return source


def replay_standard_basis(source: str) -> dict[str, int]:
    modular = source.replace("ring R=0,", f"ring R={PRIME},", 1)
    modular += (
        '\nprint("CODEX_RESULT:"+string(size(G))+":"+string(dim(G))'
        '+":"+string(vdim(G)));\n'
    )
    completed = subprocess.run(
        singular_command(),
        input=modular,
        text=True,
        capture_output=True,
        timeout=600,
        check=False,
    )
    if completed.returncode != 0 or completed.stderr.strip() or "?" in completed.stdout:
        raise AssertionError(
            f"Singular failed: rc={completed.returncode}, "
            f"stdout={completed.stdout!r}, stderr={completed.stderr!r}"
        )
    markers = [
        line.strip()
        for line in completed.stdout.splitlines()
        if line.strip().startswith("CODEX_RESULT:")
    ]
    assert len(markers) == 1
    size, dimension, vector_dimension = (
        int(value) for value in markers[0].split(":")[1:]
    )
    assert (size, dimension, vector_dimension) == (18, 0, 9)
    return {
        "prime": PRIME,
        "standard_basis_size": size,
        "local_dimension": dimension,
        "vector_space_dimension": vector_dimension,
    }


def main() -> None:
    source = regenerate_graph_slice()
    certificate = replay_standard_basis(source)
    print(
        json.dumps(
            {
                "status": "verified",
                "field": "C",
                "component": "common-active binary rank-one triangle",
                "component_dimension": 5,
                "generic_pair_profile": [4, 4, 4, 3, 3, 3],
                "kernel_endpoint_signature": [2, 2, 0, 0],
                "family_minor": "-1/6",
                "incidence_tangent_rank": 12,
                "graph_slice_generators": 15,
                "graph_slice_variables": 15,
                **certificate,
                "integral_height": 15,
                "new_component_orbit_number": 20,
                "singleton_sheet_in_component_closure": True,
                "search_used": False,
                "global_conjecture_resolved": False,
                "graph_slice_sha256": sha256(GRAPH_SLICE),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
