"""Exact integer-lattice membership and signed transport via Smith form."""

from __future__ import annotations
import sys as _bootstrap_sys
from pathlib import Path as _BootstrapPath

for _bootstrap_parent in _BootstrapPath(__file__).resolve().parents:
    if (_bootstrap_parent / "src" / "krenn_gu" / "bootstrap.py").is_file():
        _bootstrap_sys.path.insert(0, str(_bootstrap_parent / "src"))
        break
else:  # pragma: no cover - checkout contract failure
    raise RuntimeError("cannot locate repository bootstrap")

from krenn_gu.bootstrap import bootstrap as _bootstrap_repository  # noqa: E402

REPO_ROOT, HERE = _bootstrap_repository(__file__)


from typing import Sequence

from sympy import Matrix, ZZ
from sympy.polys.matrices import DomainMatrix
from sympy.polys.matrices.normalforms import smith_normal_decomp


class IntegerSignedLattice:
    """The row lattice generated by integer relation vectors.

    A relation row ``r`` represents the multiplicative equation
    ``x**r = -1``.  If the integer kernel contains no vector with odd
    coefficient sum, the parity of a representation ``v = z R`` is
    well-defined and gives the transported sign between monomials whose
    exponent difference is ``v``.
    """

    def __init__(
        self,
        rows: Sequence[Sequence[int]],
        sign_bits: Sequence[int] | None = None,
    ) -> None:
        if not rows:
            raise ValueError("integer signed lattice needs a relation")
        self.rows = tuple(tuple(map(int, row)) for row in rows)
        self.generators = len(self.rows)
        if sign_bits is None:
            self.sign_bits = (1,) * self.generators
        else:
            self.sign_bits = tuple(int(bit) % 2 for bit in sign_bits)
            if len(self.sign_bits) != self.generators:
                raise ValueError("relation sign count changed")
        self.width = len(self.rows[0])
        if any(len(row) != self.width for row in self.rows):
            raise ValueError("relation rows have different widths")
        transposed = [
            list(column) for column in zip(*self.rows, strict=True)
        ]
        matrix = DomainMatrix.from_list_sympy(
            self.width, self.generators, transposed
        ).convert_to(ZZ)
        smith, left, right = smith_normal_decomp(matrix)
        if smith != left * matrix * right:
            raise AssertionError("Smith decomposition did not replay")
        self._matrix = matrix.to_Matrix()
        self._smith = smith.to_Matrix()
        self._left = left.to_Matrix()
        self._right = right.to_Matrix()
        self._left_sparse = tuple(
            tuple(
                (column, int(self._left[row, column]))
                for column in range(self.width)
                if self._left[row, column]
            )
            for row in range(self.width)
        )
        self._right_sparse = tuple(
            tuple(
                (column, int(self._right[row, column]))
                for column in range(self.generators)
                if self._right[row, column]
            )
            for row in range(self.generators)
        )
        self.rank = sum(
            self._smith[index, index] != 0
            for index in range(min(smith.shape))
        )
        self.invariant_factors = tuple(
            abs(int(self._smith[index, index]))
            for index in range(self.rank)
        )
        self.kernel_basis = tuple(
            tuple(
                int(self._right[row, column])
                for row in range(self.generators)
            )
            for column in range(self.rank, self.generators)
        )
        for vector in self.kernel_basis:
            if self._matrix * Matrix(vector) != Matrix.zeros(
                self.width, 1
            ):
                raise AssertionError("Smith kernel vector did not replay")
        self.has_odd_kernel = any(
            sum(vector) % 2 for vector in self.kernel_basis
        )
        self.has_inconsistent_kernel = any(
            sum(
                coefficient * bit
                for coefficient, bit in zip(
                    vector, self.sign_bits, strict=True
                )
            )
            % 2
            for vector in self.kernel_basis
        )

    def coordinates(self, vector: Sequence[int]) -> list[int] | None:
        """Return one integer generator representation, or ``None``."""

        raw = tuple(map(int, vector))
        if len(raw) != self.width:
            raise ValueError("target vector has the wrong width")
        transformed = [
            sum(raw[column] * coefficient for column, coefficient in row)
            for row in self._left_sparse
        ]
        smith_coordinates = [0] * self.generators
        for index in range(self.rank):
            diagonal = int(self._smith[index, index])
            quotient, remainder = divmod(
                transformed[index], diagonal
            )
            if remainder:
                return None
            smith_coordinates[index] = quotient
        if any(
            transformed[index]
            for index in range(self.rank, self.width)
        ):
            return None
        coordinates = [
            sum(
                smith_coordinates[column] * coefficient
                for column, coefficient in row
            )
            for row in self._right_sparse
        ]
        if self._matrix * Matrix(coordinates) != Matrix(raw):
            raise AssertionError("integer lattice coordinates did not replay")
        return coordinates

    def transported_sign(self, vector: Sequence[int]) -> int | None:
        """Return ``(-1)^sum(z)`` when ``vector = z R``."""

        coordinates = self.coordinates(vector)
        if coordinates is None:
            return None
        if self.has_inconsistent_kernel:
            raise ValueError(
                "transported sign is ambiguous because the signed "
                "relation system has an inconsistent kernel dependency"
            )
        parity = sum(
            coefficient * bit
            for coefficient, bit in zip(
                coordinates, self.sign_bits, strict=True
            )
        )
        return -1 if parity % 2 else 1
