#!/usr/bin/env python3
"""Independent exact audit of the p=2 symbolic-a Q6 offset closure.

This file is deliberately self-contained.  It does not import any project
verifier, the GLD71 builder, the GLD88 family builder, GLD96, or the
exploratory p=2 script.  The fixed sparse relation supports needed by the six
displayed minors are copied as immutable data, syndrome entries are assembled
directly from those supports, and every determinant is computed by the local
fraction-free Bareiss routine below.

The audited claim is deliberately scoped.  Put p=2 in the normalized H4
GLD96/F88-offset chart, retain symbolic a and offsets B,C, and impose
Q2(q)=Q6(2,q)=0.  Let T0,...,T3 be the four GLD96 bordered seven-minors and
D0,D2 the two additional seven-minors.  The exact ideal generated by their
six reduced polynomial representatives is recomputed and asserted to have
grevlex basis [Q2/5, B, C].  Therefore every syndrome-rank-at-most-six point in this
offset chart lies at B=C=0, i.e. in F88.  GLD95 is an upstream theorem needed
for the final incidence exclusion on D(Omega*Delta); this file does not
reprove that bridge or GLD95.

This is not a global Krenn--Gu proof.  The global status remains UNRESOLVED.
"""

from __future__ import annotations

import hashlib
import json
import platform
import sys
import time

import sympy as sp
from sympy import QQ


B, C, q, a = sp.symbols("B C q a")


# These are the immutable GLD71 sparse relation supports required by the
# displayed six seven-minors.  The tuple key is the original syndrome row;
# each support entry is ((root, leaf_1, leaf_2, leaf_3), coefficient).
# No verifier/builder is imported to obtain this data.
PINNED_RELATIONS = {
    0: (((1, 1, 1, 1), 1),),
    1: (((0, 0, 0, 0), 1),),
    2: (((2, 2, 0, 0), 1), ((2, 2, 1, 1), -1)),
    3: (
        ((2, 0, 2, 0), 1),
        ((2, 1, 2, 1), -1),
    ),
    17: (
        ((0, 0, 1, 1), 1),
        ((0, 1, 0, 0), -1),
        ((1, 0, 0, 0), -1),
        ((1, 1, 0, 0), 2),
        ((1, 1, 0, 1), -1),
        ((1, 1, 1, 0), -1),
    ),
    25: (
        ((1, 1, 0, 0), 1),
        ((1, 1, 0, 1), -1),
        ((1, 1, 1, 0), -1),
        ((1, 2, 0, 0), -1),
        ((1, 2, 0, 1), 1),
        ((1, 2, 1, 0), 1),
        ((2, 1, 0, 0), -1),
        ((2, 1, 0, 1), 1),
        ((2, 1, 1, 0), 1),
        ((2, 2, 0, 0), 1),
        ((2, 2, 0, 1), -1),
        ((2, 2, 1, 0), -1),
    ),
    28: (
        ((0, 0, 1, 0), 1),
        ((0, 0, 1, 2), -1),
        ((0, 1, 0, 0), 1),
        ((0, 1, 0, 2), -1),
        ((0, 1, 1, 0), -1),
        ((0, 1, 1, 2), 1),
        ((2, 0, 1, 0), -1),
        ((2, 0, 1, 2), 1),
        ((2, 1, 0, 0), -1),
        ((2, 1, 0, 2), 1),
        ((2, 1, 1, 0), 1),
        ((2, 1, 1, 2), -1),
    ),
    31: (
        ((1, 0, 0, 0), 8),
        ((1, 0, 0, 1), -4),
        ((1, 0, 1, 0), -4),
        ((1, 0, 1, 1), 2),
        ((1, 1, 0, 0), 2),
        ((1, 1, 0, 1), -1),
        ((1, 1, 1, 0), -1),
        ((1, 1, 1, 2), 3),
        ((1, 1, 2, 1), 3),
        ((1, 2, 0, 0), -12),
        ((1, 2, 0, 1), 6),
        ((1, 2, 1, 0), 6),
        ((2, 1, 1, 1), 6),
    ),
    32: (
        ((0, 0, 0, 1), 1),
        ((0, 0, 0, 2), -3),
        ((0, 0, 1, 0), -2),
        ((0, 0, 1, 1), 4),
        ((0, 0, 2, 1), -6),
        ((0, 1, 0, 0), 1),
        ((0, 1, 0, 1), -2),
        ((0, 1, 1, 0), 4),
        ((0, 1, 1, 1), -8),
        ((0, 1, 2, 0), -6),
        ((0, 1, 2, 1), 12),
        ((0, 2, 0, 0), -3),
        ((2, 0, 0, 0), -6),
    ),
    33: (
        ((1, 0, 0, 0), 4),
        ((1, 0, 0, 1), -8),
        ((1, 0, 1, 0), -2),
        ((1, 0, 1, 1), 1),
        ((1, 0, 1, 2), 6),
        ((1, 1, 0, 0), -2),
        ((1, 1, 0, 1), 13),
        ((1, 1, 0, 2), -6),
        ((1, 1, 1, 0), -2),
        ((1, 1, 1, 2), -6),
        ((1, 1, 2, 1), 3),
        ((1, 2, 1, 1), 3),
        ((2, 0, 0, 1), 12),
        ((2, 1, 0, 1), -12),
    ),
}

SUPPORT_ROWS = tuple(sorted(PINNED_RELATIONS))


# Six seven-minors.  The first four are the GLD96 bordered minors; D0 and D2
# are the extra rank-seven detectors from the p=2 symbolic-a computation.
MINORS = {
    "T0": ((0, 1, 2, 17, 25, 31, 28), (0, 1, 3, 4, 6, 7, 8)),
    "T1": ((0, 1, 2, 17, 25, 31, 32), (0, 1, 3, 4, 6, 7, 2)),
    "T2": ((0, 1, 2, 17, 25, 31, 32), (0, 1, 3, 4, 6, 7, 5)),
    "T3": ((0, 1, 2, 17, 25, 31, 33), (0, 1, 3, 4, 6, 7, 8)),
    "D0": ((1, 17, 28, 0, 25, 31, 32), (0, 1, 2, 3, 4, 5, 6)),
    "D2": ((1, 17, 28, 0, 31, 32, 3), (0, 1, 2, 3, 4, 5, 6)),
}

EXPECTED_SUPPORT_DIGEST = (
    "c53d2c7912d87b5f46c39ec6fc64d1aaa6ab7839ad69f3bbfb6f39375b6ed1b0"
)
EXPECTED_RAW_DENOMINATORS = {
    "T0": "q*(q + 1)**3",
    "T1": "q**2*(q + 1)**2",
    "T2": "q**2*(q + 1)**3",
    "T3": "q*(q + 1)**2",
    "D0": "(q + 1)**6",
    "D2": "(q + 1)**6",
}
EXPECTED_REDUCED_HASHES = {
    "T0": "e726ee5fd5406059d95043969ad5860eda1463540696d7e4e8cf5420543508d3",
    "T1": "2fd8891db047195270f87c09c7024b5dbde4f8ed27014648ee487b27031e6ca6",
    "T2": "f84a890c3d52c92f0af7a7f753310d59c3cc9bb11ea32433c83a7d3e9bb9764e",
    "T3": "fbe10197fe9898c98389e97e4e58584d9ccf9b61bc2cbc51e959082ccfb11186",
    "D0": "652f5a57dbe12daf26a3336e8924cab9c84f607ca60f330aa2f6c54ec99a19a1",
    "D2": "2cc8f30090e21531f595608185becbb6449ee90f8f8d7b6c36e51c9b4cfc40b2",
}
EXPECTED_RAW_NUMERATOR_HASHES = {
    "T0": "e065890f74336acac357c58ac4f33d1d35b1dc200c6a27ec433efa95d07aa460",
    "T1": "dc608a637397dba5b8354e378c9b142d600693568b52210b9eb32fbebf345311",
    "T2": "959792e9c197492801071ba19dc840b0ccd88a68b39d52e1aaa34f2f66971b0b",
    "T3": "0136e071b62bcb2210310cedf5081a56b234184819711fe7f94b6f476a472cc3",
    "D0": "41338d3c103bebd24dd3862168672b108f38392fbf81a4ce01246acd3e05cb4f",
    "D2": "e9d6455fc3500387b2a40d63663d58fc531ef94b33fb016b4897f12dc8d76124",
}
EXPECTED_GREVLEX_BASIS_SREPR_SHA256 = (
    "da8b07d04dfb0dbc9935345320722fb21f9e711bb9166f82db9fb23b0f7f585f"
)


def canonical_support_digest() -> str:
    encoded = [
        [row, [[list(indices), coefficient] for indices, coefficient in PINNED_RELATIONS[row]]]
        for row in SUPPORT_ROWS
    ]
    return hashlib.sha256(json.dumps(encoded, separators=(",", ":")).encode()).hexdigest()


def h4_family(p: sp.Expr, q_value: sp.Expr, a_value: sp.Expr) -> dict[str, sp.Expr]:
    """Local transcription of the written GLD88 F88 formula."""

    d0 = p + q_value - 1
    e = 2 * p * q_value**2 - 2 * p * q_value - p - q_value**2 - 2 * q_value + 2
    nb = (
        -2 * a_value * p**2 * q_value**3
        + 3 * a_value * p**2 * q_value**2
        - 3 * a_value * p**2 * q_value
        + a_value * p**2
        + 2 * a_value * p * q_value**3
        + 2 * a_value * p
        + a_value * q_value**3
        - 3 * a_value * q_value**2
        + 3 * a_value * q_value
        - 2 * a_value
        + p**3 * q_value**2
        - p**3
        + p**2 * q_value**3
        - 3 * p**2 * q_value**2
        + p**2
        - 2 * p * q_value**3
        + 3 * p * q_value**2
        - 2 * p
        + q_value**2
        - 3 * q_value
        + 2
    )
    nc = (
        2 * a_value * p * q_value**3
        - 3 * a_value * p * q_value**2
        + 3 * a_value * p * q_value
        - a_value * p
        - a_value * q_value**3
        + 3 * a_value * q_value**2
        - 3 * a_value * q_value
        + 2 * a_value
        + p**2 * q_value**2
        - 2 * p**2 * q_value
        - 3 * p * q_value**2
        + p * q_value
        + p
        - q_value**2
        + 3 * q_value
        - 2
    )
    return {
        "s": sp.cancel((p + q_value - p * q_value) / d0),
        "b": sp.cancel(-nb / ((p**2 - p + 1) * e)),
        "c": sp.cancel(-nc / (d0 * e)),
    }


def q6(p: sp.Expr, q_value: sp.Expr) -> sp.Expr:
    return (
        2 * p**4 * q_value**2 - 2 * p**4 * q_value + p**4
        + 2 * p**3 * q_value**3 - 7 * p**3 * q_value**2 + 5 * p**3 * q_value - 2 * p**3
        + 2 * p**2 * q_value**4 - 7 * p**2 * q_value**3 + 12 * p**2 * q_value**2
        - 7 * p**2 * q_value + 2 * p**2 - 2 * p * q_value**4 + 5 * p * q_value**3
        - 7 * p * q_value**2 + 2 * p * q_value + q_value**4 - 2 * q_value**3 + 2 * q_value**2
    )


def direct_rows(leaf: sp.Matrix, rows: tuple[int, ...]) -> sp.Matrix:
    """Accumulate syndrome entries directly from the pinned supports."""

    return sp.Matrix(
        [
            [
                sp.expand(
                    sum(
                        coefficient
                        * leaf[indices[1], component]
                        * leaf[indices[2], component]
                        * leaf[indices[3], component]
                        for indices, coefficient in PINNED_RELATIONS[row]
                        if indices[0] == root
                    )
                )
                for root in range(3)
                for component in range(3)
            ]
            for row in rows
        ]
    )


def bareiss_determinant(matrix: sp.Matrix) -> sp.Expr:
    """Fraction-free Bareiss determinant in Q(q,a)[B,C]."""

    coefficient_domain = QQ.frac_field(q, a)
    work = [
        [
            sp.Poly(sp.cancel(matrix[row, column]), B, C, domain=coefficient_domain)
            for column in range(matrix.cols)
        ]
        for row in range(matrix.rows)
    ]
    previous = sp.Poly(1, B, C, domain=coefficient_domain)
    sign = 1
    size = matrix.rows
    if matrix.rows != matrix.cols:
        raise ValueError("Bareiss requires a square matrix")
    for pivot_index in range(size - 1):
        pivot_row = next(
            (row for row in range(pivot_index, size) if not work[row][pivot_index].is_zero),
            None,
        )
        if pivot_row is None:
            return sp.Integer(0)
        if pivot_row != pivot_index:
            work[pivot_index], work[pivot_row] = work[pivot_row], work[pivot_index]
            sign = -sign
        pivot = work[pivot_index][pivot_index]
        for row in range(pivot_index + 1, size):
            left = work[row][pivot_index]
            for column in range(pivot_index + 1, size):
                value = work[row][column] * pivot - left * work[pivot_index][column]
                work[row][column] = value.exquo(previous)
            work[row][pivot_index] = sp.Poly(0, B, C, domain=coefficient_domain)
        previous = pivot
    result = work[-1][-1]
    return (result if sign > 0 else -result).as_expr()


def primitive_polynomial(expression: sp.Expr) -> sp.Expr:
    """Canonical primitive polynomial over Q[B,C,q,a]."""

    numerator, denominator = sp.cancel(expression).as_numer_denom()
    if denominator.has(B, C, q, a):
        raise AssertionError(("unrecorded polynomial denominator", sp.factor(denominator)))
    polynomial = sp.Poly(sp.expand(numerator / denominator), B, C, q, a, domain=QQ)
    content, primitive = polynomial.primitive()
    primitive = primitive.monic() if primitive.total_degree() == 0 else primitive
    expression = sp.expand(primitive.as_expr())
    leading_coefficient = sp.Poly(expression, B, C, q, a, domain=QQ).LC()
    if leading_coefficient < 0:
        expression = -expression
    return sp.expand(expression)


def q2_reduce(expression: sp.Expr, q2: sp.Poly) -> tuple[sp.Expr, str]:
    """Reduce a raw rational determinant modulo Q2, retaining its denominator."""

    numerator, denominator = sp.cancel(expression).as_numer_denom()
    if denominator.has(B, C, a):
        raise AssertionError(("denominator contains a displayed variable", sp.factor(denominator)))
    denominator_poly = sp.Poly(denominator, q, domain=QQ)
    q2_base = sp.Poly(q2.as_expr(), q, domain=QQ)
    gcd = sp.gcd(denominator_poly, q2_base)
    if gcd.degree() != 0:
        raise AssertionError(("determinant denominator meets Q2", sp.factor(gcd.as_expr())))

    coefficient_domain = QQ.frac_field(B, C, a)
    q2_field = sp.Poly(q2.as_expr(), q, domain=coefficient_domain)
    numerator_poly = sp.Poly(numerator, q, domain=coefficient_domain)
    denominator_field = sp.Poly(denominator, q, domain=coefficient_domain)
    inverse = sp.invert(denominator_field, q2_field)
    reduced = (numerator_poly.rem(q2_field) * inverse).rem(q2_field).as_expr()
    reduced = sp.cancel(reduced)
    if sp.denom(reduced).has(B, C, q, a):
        raise AssertionError(("Q2 reduction introduced a parameter/displayed-variable denominator", sp.denom(reduced)))
    return primitive_polynomial(reduced), str(sp.factor(denominator))


def gate_ledger(q2: sp.Poly) -> dict[str, object]:
    p = sp.Integer(2)
    d0 = q + 1
    P = p**2 - p + 1
    L1 = p**2 + 2 * p * q - 2 * p - q
    L2 = 2 * p * q - p + q**2 - 2 * q
    e = 2 * p * q**2 - 2 * p * q - p - q**2 - 2 * q + 2
    delta = sp.expand((p - q) * d0 * P * L1 * L2 * e)
    h2 = 2 * p**2 - 2 * p + 1
    q2_poly = sp.Poly(q2.as_expr(), q, domain=QQ)
    factors = {
        "p_minus_q": p - q,
        "d0": d0,
        "P": P,
        "L1": L1,
        "L2": L2,
        "e": e,
        "Delta": delta,
        "h2_leading_coefficient": h2,
    }
    gcds = {}
    for name, factor in factors.items():
        factor_poly = sp.Poly(factor, q, domain=QQ)
        gcds[name] = str(sp.factor(sp.gcd(factor_poly, q2_poly).as_expr()))
    # det(G)=(1-a)*(q^2+2q-2)/(q+1) after p=2.  The a=1 gate is part of
    # det(G)/D(Omega), while the q-dependent part is already in Delta.
    det_g = sp.cancel((1 - a) * L2 / d0)
    return {
        "p": 2,
        "d0": str(d0),
        "P": str(P),
        "L1": str(L1),
        "L2": str(L2),
        "e": str(e),
        "Delta_factorization": str(sp.factor(delta)),
        "h2": str(h2),
        "detG_at_p2_F88_origin": str(det_g),
        "chart_denominators": {
            "s": str(d0),
            "b88": str(sp.factor(P * e)),
            "c88": str(sp.factor(d0 * e)),
            "kernel_u_v": str(sp.factor((p - q) * d0**3)),
        },
        "Q2_gate_gcds": gcds,
        "all_q_gates_coprime_to_Q2": all(value == "1" for value in gcds.values()),
    }


def canonical_basis(expressions: list[sp.Expr]) -> list[str]:
    result = []
    for expression in expressions:
        polynomial = sp.Poly(sp.expand(expression), B, C, q, a, domain=QQ)
        result.append(str(sp.expand(polynomial.monic().as_expr())))
    return sorted(result)


def check() -> dict[str, object]:
    started = time.monotonic()
    if SUPPORT_ROWS != (0, 1, 2, 3, 17, 25, 28, 31, 32, 33):
        raise AssertionError(SUPPORT_ROWS)
    if canonical_support_digest() != EXPECTED_SUPPORT_DIGEST:
        raise AssertionError("pinned sparse-support digest changed")

    p = sp.Integer(2)
    family = h4_family(p, q, a)
    leaf = sp.Matrix(
        [
            [1, 1, 1],
            [p, q, family["s"]],
            [a, 1 + family["b"] + B, 1 + family["c"] + C],
        ]
    )
    if sp.cancel(p * q + p * family["s"] + q * family["s"] - p - q - family["s"]) != 0:
        raise AssertionError("copied leaf formula does not satisfy H4")
    expected_det_g = sp.cancel((1 - a) * (q**2 + 2 * q - 2) / (q + 1))
    if sp.cancel(leaf.subs({B: 0, C: 0}).det() - expected_det_g) != 0:
        raise AssertionError("p=2 F88-origin leaf determinant identity changed")
    q2 = sp.Poly(q6(p, q), q, domain=QQ)
    expected_q2 = 5 * q**4 - 4 * q**3 + 12 * q**2 - 16 * q + 8
    if q2.as_expr() != expected_q2:
        raise AssertionError(q2.as_expr())

    gates = gate_ledger(q2)
    if not gates["all_q_gates_coprime_to_Q2"]:
        raise AssertionError(gates)

    reduced_minors: dict[str, sp.Expr] = {}
    raw_metadata: dict[str, object] = {}
    reduced_metadata: dict[str, object] = {}
    for name, (rows, columns) in MINORS.items():
        print(f"[audit] building {name}", flush=True)
        matrix = direct_rows(leaf, rows).extract(range(len(rows)), columns)
        raw = sp.cancel(bareiss_determinant(matrix))
        print(f"[audit] Bareiss complete {name}", flush=True)
        numerator, denominator = raw.as_numer_denom()
        if denominator.has(B, C, a):
            raise AssertionError((name, "unexpected denominator", sp.factor(denominator)))
        reduced, denominator_text = q2_reduce(raw, q2)
        print(f"[audit] Q2 reduction complete {name}", flush=True)
        reduced_minors[name] = reduced
        reduced_poly = sp.Poly(reduced, B, C, q, a, domain=QQ)
        raw_metadata[name] = {
            "rows": list(rows),
            "columns": list(columns),
            "raw_denominator": str(sp.factor(denominator)),
            "raw_numerator_terms": len(sp.Poly(numerator, B, C, q, a, domain=QQ).terms()),
            "raw_numerator_srepr_sha256": hashlib.sha256(sp.srepr(numerator).encode()).hexdigest(),
            "denominator_used_for_Q2_reduction": denominator_text,
        }
        if raw_metadata[name]["raw_denominator"] != EXPECTED_RAW_DENOMINATORS[name]:
            raise AssertionError((name, raw_metadata[name]["raw_denominator"]))
        delta_2 = -27 * q**2 * (q - 2) ** 2 * (q + 1) * (q**2 + 2 * q - 2)
        for factor, _multiplicity in sp.factor_list(denominator, q)[1]:
            if sp.rem(
                sp.Poly(delta_2, q, domain=QQ),
                sp.Poly(factor, q, domain=QQ),
            ) != 0:
                raise AssertionError((name, "raw denominator factor is not a Delta_2 gate", factor))
        if raw_metadata[name]["raw_numerator_srepr_sha256"] != EXPECTED_RAW_NUMERATOR_HASHES[name]:
            raise AssertionError((name, raw_metadata[name]["raw_numerator_srepr_sha256"]))
        reduced_metadata[name] = {
            "terms": len(reduced_poly.terms()),
            "total_degree": reduced_poly.total_degree(),
            "degrees": {str(variable): reduced_poly.degree(variable) for variable in (B, C, q, a)},
            "srepr_sha256": hashlib.sha256(sp.srepr(reduced).encode()).hexdigest(),
            "reduced_polynomial": str(reduced),
        }
        if reduced_metadata[name]["srepr_sha256"] != EXPECTED_REDUCED_HASHES[name]:
            raise AssertionError((name, reduced_metadata[name]["srepr_sha256"]))

    generators = [q2.as_expr() / 5, *reduced_minors.values()]
    print("[audit] computing exact grevlex basis", flush=True)
    basis = sp.groebner(generators, B, C, q, a, order="grevlex", domain=QQ)
    print("[audit] grevlex basis complete", flush=True)
    actual_basis = canonical_basis([poly.as_expr() for poly in basis.polys])
    expected_basis = canonical_basis([q2.as_expr() / 5, B, C])
    if actual_basis != expected_basis:
        raise AssertionError({"actual_basis": actual_basis, "expected_basis": expected_basis})
    if basis.reduce(B)[1] != 0 or basis.reduce(C)[1] != 0:
        raise AssertionError("B/C did not reduce to zero")
    basis_hash = hashlib.sha256(
        "\n".join(sp.srepr(sp.expand(poly.as_expr())) for poly in basis.polys).encode()
    ).hexdigest()
    if basis_hash != EXPECTED_GREVLEX_BASIS_SREPR_SHA256:
        raise AssertionError(("grevlex basis hash changed", basis_hash))

    return {
        "status": "independent_exact_p2_symbolic_a_Q6_six_minor_offset_exclusion",
        "global_conjecture": "UNRESOLVED",
        "scope": (
            "normalized GLD96/F88-offset chart at p=2, symbolic a, Q2=0; "
            "rank-at-most-six implication only, with inherited GLD95 endpoint on D(Omega*Delta)"
        ),
        "imports_project_verifiers": False,
        "construction": "pinned sparse supports, direct accumulation, local Bareiss determinants",
        "runtime_environment": {
            "python": platform.python_version(),
            "implementation": platform.python_implementation(),
            "sympy": sp.__version__,
            "platform": platform.platform(),
            "executable": sys.executable,
        },
        "recommended_containment": (
            "python tools/research/run_bounded.py --timeout-seconds 300 "
            "--memory-mb 4096 -- python "
            "claims/arbitrary-order/"
            "audit_four_root_torus_star_equal_leaf_h4_q6_p2_six_minor_offset_exclusion.py"
        ),
        "support_rows": list(SUPPORT_ROWS),
        "support_digest_sha256": canonical_support_digest(),
        "Q2": str(q2.as_expr()),
        "gate_ledger": gates,
        "raw_minor_metadata": raw_metadata,
        "reduced_minor_metadata": reduced_metadata,
        "six_reduced_polynomial_hashes": {
            name: reduced_metadata[name]["srepr_sha256"] for name in MINORS
        },
        "ideal_generators": [str(generator) for generator in generators],
        "grevlex_basis": actual_basis,
        "grevlex_basis_srepr_sha256": basis_hash,
        "exact_BC_membership": True,
        "upstream_endpoint": (
            "rank-at-most-six makes all six displayed seven-minors vanish; "
            "the exact basis forces B=C=0; GLD95 then excludes F88 incidence on D(Omega*Delta)"
        ),
        "scope_fences": [
            "R31-open E31/g0 localization is not independently reproved here",
            "the chart denominators and det(G)/D(Omega) gates are retained",
            "GLD75/GLD86 bridge and GLD95 are upstream dependencies",
            "arbitrary p, other H4 charts, Fitting, and global resolution remain open",
        ],
        "elapsed_seconds": round(time.monotonic() - started, 3),
    }


def main() -> None:
    result = check()
    print("independent p=2 symbolic-a Q6 six-minor offset audit: PASS")
    print(json.dumps(result, indent=2, sort_keys=True, default=str))


if __name__ == "__main__":
    main()
