#!/usr/bin/env python3
"""Verify and regenerate the portable GLD101 R110 P8 B-open leaf.

This verifier deliberately proves only one scoped computational statement.  On
the normalized a=0, R110=0, Q6=0, B-open chart, the ideal generated by the
eight actual minors T0,T1,T2,T3,D0,Y0,Y1,X3 and z*B-1 is the unit ideal.  It
rebuilds the compact nine-minor coefficient seam from the pinned GLD71/GLD88
parents, derives R110 from the six-selector norm, checks all coefficient and
Delta gates, and deterministically emits the exact Singular standard-basis
input used for the final unit-ideal calculation.

The C-open calculation is corroborative and is not part of this portable leaf.
The six-minor P6 experiment was inconclusive.  No selector converse, endpoint
closure, theorem promotion, full-E31 claim, or global Krenn--Gu resolution is
asserted here.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import sys
from typing import Any, Sequence

import sympy as sp
from sympy import QQ


ROOT = Path(__file__).resolve().parents[2]
BASE_VERIFIER = ROOT / "claims" / "arbitrary-order" / (
    "verify_four_root_torus_star_equal_leaf_h4_q6_a0_six_selector_norm_cover.py"
)
CERTIFICATE = ROOT / "claims" / "arbitrary-order" / "certificates" / (
    "GLD101_A0_R110_P8_BOPEN_PORTABLE_CERTIFICATE.json"
)

EXPECTED_BASE_LF_SHA256 = (
    "c36d618651b92621627961d3004128f39cb43e522a76256c74b1141baf9d1a3c"
)
EXPECTED_CERTIFICATE_LF_SHA256 = (
    "bdf84e09be8e4d7f76a0d05b050957acd2ef9b95d1e55a6fafe3f9d465c1c32b"
)
EXPECTED_SUPPORT_DIGEST = (
    "c53d2c7912d87b5f46c39ec6fc64d1aaa6ab7839ad69f3bbfb6f39375b6ed1b0"
)
EXPECTED_Q6_SREPR_SHA256 = (
    "2ed58764e7c50c8e1510a93b32d2515a9297c03dfe297fed8d9abe5f8e9d71a7"
)
EXPECTED_DIRECT_GENERATOR_DIGEST = (
    "8ce1f9037e428291f123237df7782968b07ee230f4e39856b25e889c0a06359b"
)
EXPECTED_R110_SHA256 = (
    "1ae5a3e502f686d484b757db27d6f70b3ff535792edb65ceb40c2bd455410016"
)
EXPECTED_RESULTANT_TEXT_SHA256 = (
    "1192e8cfe113b732e6b1dfa67f06c45ed6317437f14ccc520f5c3db5335f2790"
)
EXPECTED_LINEAR_C0_SHA256 = (
    "7592da3baafec83829e532a52fdb18500902134a77c8e07b1c57e62a1557c52f"
)
EXPECTED_LINEAR_C1_SHA256 = (
    "eccd307c79046e6b55bba6852feee2b24515c34c38c3fc591e1624ba22acd2ff"
)
EXPECTED_SINGULAR_SOURCE_SHA256 = (
    "a8b84e4d8cf2cd7768ab4d945a403ac80200adef0019de6a793bb565756b3bd5"
)

p, q = sp.symbols("p q")
GENERATOR_ORDER = ("T0", "T1", "T2", "T3", "D0", "D2", "Y0", "Y1", "X3")
EIGHT_NAMES = ("T0", "T1", "T2", "T3", "D0", "Y0", "Y1", "X3")
SIX_NAMES = ("T0", "T1", "T2", "T3", "Y1", "X3")
SIX_COLUMNS = ((0, 1), (1, 0), (1, 1), (2, 0), (2, 1), (3, 0))
RSTAR = (0, 1, 17, 28, 31, 32, 33)
NAMED = {
    "T0": ((0, 1, 2, 17, 25, 31, 28), (0, 1, 3, 4, 6, 7, 8)),
    "T1": ((0, 1, 2, 17, 25, 31, 32), (0, 1, 3, 4, 6, 7, 2)),
    "T2": ((0, 1, 2, 17, 25, 31, 32), (0, 1, 3, 4, 6, 7, 5)),
    "T3": ((0, 1, 2, 17, 25, 31, 33), (0, 1, 3, 4, 6, 7, 8)),
    "D0": ((1, 17, 28, 0, 25, 31, 32), (0, 1, 2, 3, 4, 5, 6)),
    "D2": ((1, 17, 28, 0, 31, 32, 3), (0, 1, 2, 3, 4, 5, 6)),
}
EXTRA = {
    "Y0": (0, 1, 2, 3, 4, 5, 6),
    "Y1": (0, 1, 3, 4, 5, 6, 7),
    "X3": (0, 1, 2, 3, 4, 6, 7),
}


class PortableLeafError(RuntimeError):
    """Fail-closed source, arithmetic, certificate, or solver-source drift."""


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def lf_sha256(path: Path) -> str:
    return sha256_bytes(path.read_bytes().replace(b"\r\n", b"\n"))


def load_base() -> Any:
    if lf_sha256(BASE_VERIFIER) != EXPECTED_BASE_LF_SHA256:
        raise PortableLeafError("pinned GLD101 arithmetic verifier drift")
    spec = importlib.util.spec_from_file_location(
        "gld101_norm_cover_for_r110_portable", BASE_VERIFIER
    )
    if spec is None or spec.loader is None:
        raise PortableLeafError(f"cannot import {BASE_VERIFIER}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def coefficient_expression(value: Any) -> sp.Expr:
    return sp.cancel(sp.sympify(value.as_expr()))


def serialize_generators(generators: dict[str, Any]) -> dict[str, Any]:
    record: dict[str, Any] = {}
    for name in GENERATOR_ORDER:
        record[name] = {
            f"{b_degree},{c_degree}": [
                str(coefficient_expression(item)) for item in coefficient
            ]
            for (b_degree, c_degree), coefficient in sorted(
                generators[name].terms.items()
            )
        }
    return record


def direct_generator_digest(generators: dict[str, Any]) -> str:
    payload: list[Any] = []
    for name in GENERATOR_ORDER:
        terms = []
        for exponent, coefficient in sorted(generators[name].terms.items()):
            slots = []
            for item in coefficient:
                numerator, denominator = coefficient_expression(item).as_numer_denom()
                slots.append([str(numerator), str(denominator)])
            terms.append([list(exponent), slots])
        payload.append([name, terms])
    encoded = json.dumps(payload, separators=(",", ":")).encode("ascii")
    return sha256_bytes(encoded)


def p_polynomial(expression: object) -> sp.Poly:
    return sp.Poly(sp.sympify(expression), p, domain=QQ)


def primitive_integer_polynomial(expression: object) -> sp.Poly:
    polynomial = p_polynomial(expression)
    denominators = [sp.denom(coefficient) for coefficient in polynomial.all_coeffs()]
    scale = sp.ilcm(*[int(value) for value in denominators])
    integer = sp.Poly(sp.expand(scale * polynomial.as_expr()), p, domain=sp.ZZ)
    _content, primitive = integer.primitive()
    if primitive.LC() < 0:
        primitive = -primitive
    return sp.Poly(primitive.as_expr(), p, domain=QQ)


def derive_r110(resultant: sp.Poly) -> tuple[sp.Poly, int]:
    _content, factors = sp.factor_list(resultant.as_expr(), p)
    candidates = []
    for factor, exponent in factors:
        if sp.degree(factor, p) == 110:
            candidates.append((primitive_integer_polynomial(factor), int(exponent)))
    if len(candidates) != 1:
        raise PortableLeafError(f"expected one degree-110 factor, found {len(candidates)}")
    factor, multiplicity = candidates[0]
    factor_hash = sha256_bytes(str(sp.expand(factor.as_expr())).encode("ascii"))
    if factor_hash != EXPECTED_R110_SHA256:
        raise PortableLeafError(f"R110 signature mismatch: {factor_hash}")
    if multiplicity != 1:
        raise PortableLeafError(f"R110 multiplicity drift: {multiplicity}")
    return factor, multiplicity


def reduce_q_polynomial(expression: sp.Expr, factor: sp.Poly) -> sp.Expr:
    result = sp.Integer(0)
    polynomial = sp.Poly(expression, q, domain=QQ.frac_field(p))
    for (q_degree,), coefficient in polynomial.terms():
        reduced = p_polynomial(str(coefficient)).rem(factor)
        result += reduced.as_expr() * q**q_degree
    return sp.expand(result)


def field_multiply(left: sp.Poly, right: sp.Poly, factor: sp.Poly) -> sp.Poly:
    return (left * right).rem(factor)


def field_power(value: sp.Poly, exponent: int, factor: sp.Poly) -> sp.Poly:
    result = sp.Poly(1, p, domain=QQ)
    base = value.rem(factor)
    power = exponent
    while power:
        if power & 1:
            result = field_multiply(result, base, factor)
        power >>= 1
        if power:
            base = field_multiply(base, base, factor)
    return result


def homogeneous_root_evaluation(
    expression: sp.Expr, c0: sp.Poly, c1: sp.Poly, factor: sp.Poly
) -> sp.Poly:
    polynomial = sp.Poly(expression, q, domain=QQ.frac_field(p))
    degree = int(polynomial.degree())
    total = sp.Poly(0, p, domain=QQ)
    for (q_degree,), coefficient in polynomial.terms():
        coefficient_poly = p_polynomial(str(coefficient)).rem(factor)
        term = field_multiply(
            coefficient_poly,
            field_power(-c0, q_degree, factor),
            factor,
        )
        term = field_multiply(
            term,
            field_power(c1, degree - q_degree, factor),
            factor,
        )
        total = (total + term).rem(factor)
    return total


def singular_term(coefficient: Any, exponents: tuple[int, int, int, int]) -> str:
    numerator, denominator = sp.fraction(sp.Rational(coefficient))
    piece = f"({numerator}/{denominator})"
    for variable, exponent in zip(("p", "q", "B", "C"), exponents):
        if exponent:
            piece += "*" + variable
            if exponent != 1:
                piece += f"^{int(exponent)}"
    return piece


def singular_pq(expression: sp.Expr) -> str:
    terms = []
    for (p_degree, q_degree), coefficient in sp.Poly(
        sp.expand(expression), p, q, domain=QQ
    ).terms():
        terms.append(singular_term(coefficient, (p_degree, q_degree, 0, 0)))
    return " + ".join(terms) if terms else "0"


def hard_generator_texts(
    generators: dict[str, Any], factor: sp.Poly
) -> tuple[dict[str, str], dict[str, int]]:
    texts: dict[str, str] = {}
    denominator_gcd_degrees: dict[str, int] = {}
    for name in EIGHT_NAMES:
        slots = [
            coefficient_expression(item)
            for coefficient in generators[name].terms.values()
            for item in coefficient
        ]
        denominator_product = sp.Poly(1, p, domain=QQ)
        for item in slots:
            _numerator, denominator = item.as_numer_denom()
            denominator_product *= p_polynomial(denominator)
        denominator_gcd_degrees[name] = int(
            sp.gcd(denominator_product, factor).degree()
        )
        terms: list[str] = []
        for (b_degree, c_degree), coefficient in sorted(
            generators[name].terms.items()
        ):
            value = sp.Integer(0)
            for q_degree, item in enumerate(coefficient):
                numerator, denominator = coefficient_expression(item).as_numer_denom()
                quotient, remainder = sp.div(
                    denominator_product, p_polynomial(denominator)
                )
                if not remainder.is_zero:
                    raise PortableLeafError(
                        f"{name} coefficient denominator product is not exact"
                    )
                value += (p_polynomial(numerator) * quotient).as_expr() * q**q_degree
            polynomial = sp.Poly(value, q, domain=QQ.frac_field(p))
            for (q_degree,), coefficient in polynomial.terms():
                reduced = p_polynomial(str(coefficient)).rem(factor)
                for (p_degree,), p_coefficient in reduced.terms():
                    terms.append(
                        singular_term(
                            p_coefficient,
                            (p_degree, q_degree, b_degree, c_degree),
                        )
                    )
        texts[name] = " + ".join(terms) if terms else "0"
    if any(degree != 0 for degree in denominator_gcd_degrees.values()):
        raise PortableLeafError("an actual-minor coefficient denominator meets R110")
    return texts, denominator_gcd_degrees


def build_singular_source(
    factor: sp.Poly,
    q6_reduced: sp.Expr,
    six_reduced: sp.Expr,
    relation: sp.Expr,
    generator_texts: dict[str, str],
) -> str:
    r110_text = str(sp.expand(factor.as_expr())).replace("**", "^")
    mathematical_generators = [
        singular_pq(q6_reduced),
        singular_pq(six_reduced),
        singular_pq(relation),
        *[generator_texts[name] for name in EIGHT_NAMES],
    ]
    lines = [
        'LIB "elim.lib";',
        "ring rg=0,(p),dp;",
        f"poly R110={r110_text};",
        "poly R110Gate=p*(p-1)*(p^2-p+1)*(2*p^2-2*p+1);",
        "poly R110GateGcd=gcd(R110,R110Gate);",
        'print("QSUB_R110_GATE_GCD_DEGREE="+string(deg(R110GateGcd)));',
        'if (deg(R110GateGcd)!=0) { print("QSUB_FATAL_R110_GATE_GCD"); exit; }',
        (
            'print("QSUB_RESULTANT_IDENTITY_SHA256='
            f'{EXPECTED_RESULTANT_TEXT_SHA256}");'
        ),
        'print("QSUB_DELTA_UNIT_BY_RESULTANT=1");',
        "ring r=(0,p),(q,z,B,C),dp;",
        f"minpoly={r110_text};",
        "option(redSB);",
        "ideal I=",
        *[f"  {text}," for text in mathematical_generators],
        "  z*B-1;",
        "poly relation=I[3];",
        "poly common_gcd=gcd(I[1],I[2]);",
        "ideal relation_basis=std(ideal(relation));",
        "poly c0poly=subst(relation,q,0);",
        (
            'if (deg(relation)!=1) { print("QSUB_FATAL_RELATION_DEGREE"); '
            "exit; }"
        ),
        (
            'if (deg(common_gcd)!=1) { print("QSUB_FATAL_GCD_DEGREE"); '
            "exit; }"
        ),
        "number c0=leadcoef(c0poly);",
        "number c1=leadcoef(relation);",
        'if (c1==0) { print("QSUB_FATAL_C1_ZERO"); exit; }',
        "number qroot=-c0/c1;",
        "poly q6_at_root=subst(I[1],q,qroot);",
        "poly six_at_root=subst(I[2],q,qroot);",
        "poly relation_at_root=subst(I[3],q,qroot);",
        'print("QSUB_GCD_DEGREE="+string(deg(common_gcd)));',
        (
            'print("QSUB_RELATION_DIVIDES_Q6="+'
            "string(reduce(I[1],relation_basis)==0));"
        ),
        (
            'print("QSUB_RELATION_DIVIDES_SIX="+'
            "string(reduce(I[2],relation_basis)==0));"
        ),
        'print("QSUB_C1_NONZERO="+string(c1!=0));',
        'print("QSUB_Q6_ZERO="+string(q6_at_root==0));',
        'print("QSUB_SIX_ZERO="+string(six_at_root==0));',
        'print("QSUB_RELATION_ZERO="+string(relation_at_root==0));',
        'print("QSUB_ROOTCHECK_OK=1");',
        (
            "ideal J=subst(I[4],q,qroot),subst(I[5],q,qroot),"
            "subst(I[6],q,qroot),subst(I[7],q,qroot),"
            "subst(I[8],q,qroot),subst(I[9],q,qroot),"
            "subst(I[10],q,qroot),subst(I[11],q,qroot),I[12];"
        ),
        'print("QSUB_J_SIZE="+string(size(J)));',
        "ideal G=std(J);",
        'print("QSUB_G_SIZE="+string(size(G)));',
        (
            'if (reduce(1,G)==0) { print("QSUB_UNIT=1"); } '
            'else { print("QSUB_UNIT=0"); }'
        ),
        "exit;",
    ]
    source = "\n".join(lines) + "\n"
    if len(lines) != 52:
        raise PortableLeafError(f"Singular source line count drift: {len(lines)}")
    digest = sha256_bytes(source.encode("utf-8"))
    if digest != EXPECTED_SINGULAR_SOURCE_SHA256:
        raise PortableLeafError(f"Singular source signature mismatch: {digest}")
    return source


def actual_minor_definitions() -> dict[str, dict[str, list[int]]]:
    definitions = {}
    for name in GENERATOR_ORDER:
        rows, columns = NAMED[name] if name in NAMED else (RSTAR, EXTRA[name])
        definitions[name] = {"rows": list(rows), "columns": list(columns)}
    return definitions


def reconstruct() -> tuple[dict[str, Any], str, dict[str, Any]]:
    base = load_base()
    source_manifest = base.pinned_source_manifest()
    algebra, rows, chart, support_digest = base.q6_and_source()
    if support_digest != EXPECTED_SUPPORT_DIGEST:
        raise PortableLeafError("tracked support digest mismatch")
    generators = base.build_generators(algebra, rows)
    if tuple(generators) != GENERATOR_ORDER:
        raise PortableLeafError("actual-minor generator order drift")
    if generators["D2"].terms:
        raise PortableLeafError("D2 is not identically zero on a=0")

    generator_digest = direct_generator_digest(generators)
    if generator_digest != EXPECTED_DIRECT_GENERATOR_DIGEST:
        raise PortableLeafError(f"direct generator digest mismatch: {generator_digest}")
    coefficient_tables = serialize_generators(generators)

    six = base.selector_det(
        algebra, generators, SIX_NAMES, SIX_COLUMNS, "R110 portable six-selector"
    )
    if algebra.is_zero(six):
        raise PortableLeafError("six-selector determinant vanished")
    six_slots = [coefficient_expression(item) for item in six]
    six_numerator = sp.expand(
        sum(
            item.as_numer_denom()[0] * q**index
            for index, item in enumerate(six_slots)
        )
    )
    q6 = base.q6_expression()
    resultant = sp.Poly(sp.resultant(q6, six_numerator, q), p, domain=QQ)
    factor_raw, multiplicity = derive_r110(resultant)
    factor = factor_raw.monic()
    if not sp.Poly(factor_raw.as_expr(), p, modulus=41).is_irreducible:
        raise PortableLeafError("R110 mod-41 irreducibility witness failed")

    gate = sp.Poly(
        p * (p - 1) * (p**2 - p + 1) * (2 * p**2 - 2 * p + 1),
        p,
        domain=QQ,
    )
    gate_degree = int(sp.gcd(factor_raw, gate).degree())
    if gate_degree != 0:
        raise PortableLeafError("R110 meets an excluded coefficient or Delta gate")

    subresultants = sp.subresultants(q6, six_numerator, q)
    linear = next(item for item in subresultants if sp.Poly(item, q).degree() == 1)
    linear_poly = sp.Poly(linear, q, domain=QQ.frac_field(p))
    c0 = p_polynomial(str(linear_poly.coeff_monomial(1))).rem(factor)
    c1 = p_polynomial(str(linear_poly.coeff_monomial(q))).rem(factor)
    c0_hash = sha256_bytes(str(c0.as_expr()).encode("ascii"))
    c1_hash = sha256_bytes(str(c1.as_expr()).encode("ascii"))
    if c0_hash != EXPECTED_LINEAR_C0_SHA256:
        raise PortableLeafError(f"linear c0 signature mismatch: {c0_hash}")
    if c1_hash != EXPECTED_LINEAR_C1_SHA256 or c1.is_zero:
        raise PortableLeafError(f"linear c1 signature mismatch: {c1_hash}")

    q6_reduced = reduce_q_polynomial(q6, factor)
    six_reduced = reduce_q_polynomial(six_numerator, factor)
    relation = sp.expand(c0.as_expr() + c1.as_expr() * q)
    root_checks = {
        "q6": homogeneous_root_evaluation(q6_reduced, c0, c1, factor).is_zero,
        "six_selector": homogeneous_root_evaluation(
            six_reduced, c0, c1, factor
        ).is_zero,
        "linear_relation": homogeneous_root_evaluation(
            relation, c0, c1, factor
        ).is_zero,
    }
    if not all(root_checks.values()):
        raise PortableLeafError(f"R110 linear-root gate failed: {root_checks}")

    delta = base.delta_expression(chart)
    expected_delta_resultant = sp.expand(
        27648
        * p**6
        * (p - 1) ** 6
        * (p**2 - p + 1) ** 19
        * (2 * p**2 - 2 * p + 1)
    )
    if sp.expand(sp.resultant(q6, delta, q) - expected_delta_resultant) != 0:
        raise PortableLeafError("Q6/Delta resultant identity failed")
    resultant_text = "27648*p^6*(p-1)^6*(p^2-p+1)^19*(2*p^2-2*p+1)"
    if sha256_bytes(resultant_text.encode("ascii")) != EXPECTED_RESULTANT_TEXT_SHA256:
        raise PortableLeafError("Q6/Delta resultant text signature mismatch")

    generator_texts, denominator_gcd_degrees = hard_generator_texts(
        generators, factor
    )
    singular_source = build_singular_source(
        factor_raw, q6_reduced, six_reduced, relation, generator_texts
    )

    payload: dict[str, Any] = {
        "schema_version": 1,
        "certificate_id": "GLD101-A0-R110-P8-B-open-portable-unit-leaf",
        "status": "scoped_portable_exact_leaf_certificate",
        "global_conjecture": "UNRESOLVED",
        "mathematical_scope": {
            "branch": "a=0, R110(p)=0, Q6(p,q)=0",
            "open": "D(B*H2*Delta) on the normalized equal-leaf H4 chart",
            "load_bearing_chart": "B-open",
            "corroborative_only": "The accepted C-open replay is not a dependency of this package.",
            "ideal_generators": [
                "Q6",
                "six_selector",
                "linear_q_relation",
                *EIGHT_NAMES,
                "z*B-1",
            ],
            "conclusion": (
                "The eight-minor B-open q-substituted ideal has standard basis [1]."
            ),
            "nonclaims": [
                "The six-minor P6 mechanism remains inconclusive.",
                "No selected-minor converse is asserted.",
                "No endpoint or physical rank point is closed by this leaf alone.",
                "No theorem, frontier, full-E31, or global claim is promoted.",
            ],
        },
        "portable_inputs": {
            "canonical_sources": {
                "GLD71": {
                    "path": (
                        "claims/arbitrary-order/"
                        "verify_four_root_torus_star_punctured_syndrome_and_"
                        "eisenstein_norm_gate.py"
                    ),
                    "lf_sha256": source_manifest["GLD71"]["lf_sha256"],
                },
                "GLD88": {
                    "path": (
                        "claims/arbitrary-order/verify_four_root_torus_star_"
                        "equal_leaf_h4_generic_rank_six_common_row_kernel_"
                        "exclusion.py"
                    ),
                    "lf_sha256": source_manifest["GLD88"]["lf_sha256"],
                },
                "GLD101_norm_cover": {
                    "path": (
                        "claims/arbitrary-order/verify_four_root_torus_star_"
                        "equal_leaf_h4_q6_a0_six_selector_norm_cover.py"
                    ),
                    "lf_sha256": EXPECTED_BASE_LF_SHA256,
                },
            },
            "support_rows": list(base.SUPPORT_ROWS),
            "support_digest": support_digest,
            "q6_srepr_sha256": EXPECTED_Q6_SREPR_SHA256,
            "path_policy": "repository-relative inputs only",
        },
        "actual_minors": {
            "generator_order": list(GENERATOR_ORDER),
            "eight_actual_minor_names": list(EIGHT_NAMES),
            "d2_role": "canonical zero-table control; excluded from P8",
            "definitions": actual_minor_definitions(),
            "coefficient_ring": "QQ(p)[q]/(Q6), sparse in B,C",
            "coefficient_tables": coefficient_tables,
            "direct_generator_digest": generator_digest,
        },
        "six_selector": {
            "names": list(SIX_NAMES),
            "columns": [list(item) for item in SIX_COLUMNS],
            "q_slot_sha256": [
                sha256_bytes(str(item).encode("ascii")) for item in six_slots
            ],
            "resultant_degree_p": int(resultant.degree()),
            "r110_multiplicity": multiplicity,
        },
        "r110": {
            "polynomial": str(sp.expand(factor_raw.as_expr())),
            "degree": 110,
            "sha256": EXPECTED_R110_SHA256,
            "mod41_irreducible": True,
            "excluded_gate": "p*(p-1)*(p^2-p+1)*(2*p^2-2*p+1)",
            "excluded_gate_gcd_degree": gate_degree,
            "q6_delta_resultant": resultant_text,
            "q6_delta_resultant_sha256": EXPECTED_RESULTANT_TEXT_SHA256,
            "delta_is_unit": True,
            "linear_relation": {
                "c0": str(c0.as_expr()),
                "c1": str(c1.as_expr()),
                "c0_sha256": c0_hash,
                "c1_sha256": c1_hash,
                "c1_nonzero": True,
                "root_checks": root_checks,
            },
            "actual_minor_denominator_gcd_degrees": denominator_gcd_degrees,
            "all_actual_minor_denominators_are_units": True,
        },
        "singular_standard_basis": {
            "chart": "B",
            "inverse_equation": "z*B-1",
            "source_sha256": EXPECTED_SINGULAR_SOURCE_SHA256,
            "source_line_count": 52,
            "source_generation": "deterministic and repository-local",
            "expected_markers": [
                "QSUB_R110_GATE_GCD_DEGREE=0",
                (
                    "QSUB_RESULTANT_IDENTITY_SHA256="
                    + EXPECTED_RESULTANT_TEXT_SHA256
                ),
                "QSUB_DELTA_UNIT_BY_RESULTANT=1",
                "QSUB_GCD_DEGREE=1",
                "QSUB_RELATION_DIVIDES_Q6=1",
                "QSUB_RELATION_DIVIDES_SIX=1",
                "QSUB_C1_NONZERO=1",
                "QSUB_Q6_ZERO=1",
                "QSUB_SIX_ZERO=1",
                "QSUB_RELATION_ZERO=1",
                "QSUB_ROOTCHECK_OK=1",
                "QSUB_J_SIZE=9",
                "QSUB_G_SIZE=1",
                "QSUB_UNIT=1",
            ],
            "fresh_bounded_run_required": True,
            "large_source_committed": False,
            "solver_log_committed": False,
        },
        "evidence_lineage": {
            "accepted_preparation": {
                "checker_sha256": (
                    "3e763ace146b93b4c3b9b160ce04aaadc3f95755d3f043403626d1d3e1bd3855"
                ),
                "artifact_sha256": (
                    "8bcd01af422f4a20dc54d5538f3609267f25dd17203b76d1f197e60c76691ab8"
                ),
                "role": "historical corroboration; not a package dependency",
            },
            "accepted_final_cross_audit": {
                "checker_sha256": (
                    "ae848e8d41792937310d5b2e5c615e665501c0c67aff5385fdd23e32b20f4c33"
                ),
                "artifact_sha256": (
                    "a930e4103050da3c612cfc2cf792561d02e54e5929859fe8172b18955440ea11"
                ),
                "role": "historical corroboration; not a package dependency",
            },
            "quarantined_non_evidence": [
                {
                    "event_id": "kgc_01M1B8SW50MBK7D38NJGBB2GE8",
                    "checker_sha256": (
                        "89697d88ed620201a3b9bee67069d49b036010d787e792797af3d7a2c67060ae"
                    ),
                    "reason": "preparation v1 support-manifest mismatch",
                },
                {
                    "event_id": "kgc_01M1B9217RNZSEHP8Y1GPHH3BH",
                    "checker_sha256": (
                        "110cd356049e5e6d3b60ede6d852472d737c3de0e4c4283cd65921c1dfde7691"
                    ),
                    "reason": "preparation v2 hard-guard parser assumption",
                },
                {
                    "event_id": "kgc_01M1BBB92WYJ1FBNB3N3E7YTYD",
                    "source_sha256": (
                        "c121bea8255e7a86619d35805bb254bca4d7e0c403fe19ce6fca97b1b772a5d4"
                    ),
                    "reason": "P6 compact-kernel run inconclusive under its bound",
                },
            ],
        },
        "independence": {
            "primary_route": (
                "rebuild through the hash-pinned GLD101 quotient implementation"
            ),
            "audit_route": (
                "direct 37x9 syndrome and actual-minor determinants with a locally "
                "transcribed H4 chart; no import of this verifier"
            ),
            "external_runtime_inputs": [],
        },
    }
    runtime = {
        "status": "exact_scoped_GLD101_R110_P8_B_open_portable_reconstruction",
        "global_conjecture": "UNRESOLVED",
        "certificate_id": payload["certificate_id"],
        "direct_generator_digest": generator_digest,
        "singular_source_sha256": EXPECTED_SINGULAR_SOURCE_SHA256,
        "r110_sha256": EXPECTED_R110_SHA256,
        "r110_multiplicity": multiplicity,
        "denominator_gcd_degrees": denominator_gcd_degrees,
        "root_checks": root_checks,
        "scope": "P8 B-open unit-ideal leaf only",
    }
    return payload, singular_source, runtime


def canonical_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def verify_tracked_certificate(expected: dict[str, Any]) -> str:
    if not CERTIFICATE.is_file():
        raise PortableLeafError(f"missing tracked certificate: {CERTIFICATE}")
    digest = lf_sha256(CERTIFICATE)
    if digest != EXPECTED_CERTIFICATE_LF_SHA256:
        raise PortableLeafError(f"tracked certificate signature mismatch: {digest}")
    try:
        observed = json.loads(CERTIFICATE.read_text(encoding="utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise PortableLeafError("tracked certificate is not strict UTF-8 JSON") from exc
    if observed != expected:
        raise PortableLeafError("tracked certificate differs from exact reconstruction")
    return digest


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit-source", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--write-certificate",
        action="store_true",
        help="write the deterministic certificate instead of checking its pin",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    payload, source, runtime = reconstruct()
    rendered_certificate = canonical_json(payload)
    if args.write_certificate:
        CERTIFICATE.parent.mkdir(parents=True, exist_ok=True)
        CERTIFICATE.write_text(rendered_certificate, encoding="utf-8", newline="\n")
        certificate_sha = sha256_bytes(rendered_certificate.encode("utf-8"))
    else:
        certificate_sha = verify_tracked_certificate(payload)
    if args.emit_source:
        args.emit_source.parent.mkdir(parents=True, exist_ok=True)
        args.emit_source.write_text(source, encoding="utf-8", newline="\n")
    runtime["certificate_lf_sha256"] = certificate_sha
    text = canonical_json(runtime)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8", newline="\n")
    print("GLD101 R110 P8 B-open portable reconstruction: PASS")
    print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
