#!/usr/bin/env python3
"""Verify the portable GLD101 d2 B-open compact unit-ideal leaf.

This checker consumes only the tracked JSON certificate.  It validates the
exact six reduced selected-minor equations at p=i, the Q6/Delta and H2 gates,
the coefficientwise-conjugate p=-i branch, and the deterministic Singular
program whose compact ideal is generated by Q6, T3, Y1, X3, and
z*B*Delta-1.  ``--emit-singular`` writes that solver input for a separately
bounded replay; no solver output is trusted or bundled here.

The result is only a selected-necessary-minor leaf on the normalized a=0,
p^2+1=0, B-open chart.  It supplies no selector converse, B=0 or C-open
coverage, endpoint/physical statement, P6/P8 theorem, arbitrary-a result,
full-E31 closure, or global Krenn--Gu resolution.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
from typing import Any, Sequence

import sympy as sp
from sympy import QQ


ROOT = Path(__file__).resolve().parents[2]
CERTIFICATE = ROOT / "claims" / "arbitrary-order" / "certificates" / (
    "GLD101_A0_D2_BOPEN_T3_Y1_X3_PORTABLE_CERTIFICATE.json"
)

EXPECTED_CERTIFICATE_LF_SHA256 = (
    "e4d0c5a07a930d8c4305a897e613b73185d48df885f9907f0e67a41fc593338c"
)
EXPECTED_SINGULAR_SOURCE_SHA256 = (
    "58530b32e87ff5a4198478c375755ed0452a4c6351ee234872796155c2dd4199"
)
SELECTORS = ("T0", "T1", "T2", "T3", "Y1", "X3")
COMPACT_CORE = ("T3", "Y1", "X3")
q, B, t = sp.symbols("q B t")
p = sp.symbols("p")


class PortableD2Error(RuntimeError):
    """Fail-closed certificate, arithmetic, scope, or source mismatch."""


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def lf_sha256(path: Path) -> str:
    return sha256_bytes(path.read_bytes().replace(b"\r\n", b"\n"))


def load_certificate() -> dict[str, Any]:
    digest = lf_sha256(CERTIFICATE)
    if digest != EXPECTED_CERTIFICATE_LF_SHA256:
        raise PortableD2Error(f"certificate LF hash mismatch: {digest}")
    raw = CERTIFICATE.read_bytes().replace(b"\r\n", b"\n")
    payload = json.loads(raw.decode("utf-8"))
    canonical = (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode()
    if raw != canonical:
        raise PortableD2Error("certificate is not canonical sorted JSON")
    return payload


def parse_singular_polynomial(text: str, variables: Sequence[sp.Symbol]) -> sp.Poly:
    python_text = re.sub(r"\bi\b", "I", text.replace("^", "**"))
    expression = sp.sympify(
        python_text,
        locals={"I": sp.I, "q": q, "B": B, "t": t},
    )
    if expression.free_symbols - set(variables):
        raise PortableD2Error(
            f"unexpected symbols in polynomial: {expression.free_symbols}"
        )
    return sp.Poly(sp.expand(expression), *variables, extension=sp.I)


def gaussian_polynomial_digest(polynomial: sp.Poly) -> str:
    encoded = []
    for monomial, coefficient in polynomial.terms():
        real, imaginary = sp.expand(coefficient).as_real_imag()
        real = sp.Rational(real)
        imaginary = sp.Rational(imaginary)
        encoded.append(
            [
                list(monomial),
                int(real.p),
                int(real.q),
                int(imaginary.p),
                int(imaginary.q),
            ]
        )
    return sha256_bytes(json.dumps(encoded, separators=(",", ":")).encode("ascii"))


def integral_gaussian_polynomial(polynomial: sp.Poly) -> sp.Poly:
    """Apply the accepted positive-rational primitive Gaussian scaling."""
    denominator_lcm = 1
    components: list[tuple[sp.Rational, sp.Rational]] = []
    for coefficient in polynomial.coeffs():
        real, imaginary = sp.expand(coefficient).as_real_imag()
        pair = (sp.Rational(real), sp.Rational(imaginary))
        components.append(pair)
        denominator_lcm = sp.ilcm(
            denominator_lcm, int(pair[0].q), int(pair[1].q)
        )
    common = 0
    for value in (
        abs(int(component * denominator_lcm))
        for pair in components
        for component in pair
        if component != 0
    ):
        common = sp.igcd(common, value)
    if common == 0:
        raise PortableD2Error("cannot normalize a zero Gaussian polynomial")
    expression = sp.expand(
        polynomial.as_expr() * sp.Rational(denominator_lcm, common)
    )
    return sp.Poly(expression, *polynomial.gens, extension=sp.I)


def q6_expression(p_value: sp.Expr, q_value: sp.Expr) -> sp.Expr:
    return (
        2 * p_value**4 * q_value**2
        - 2 * p_value**4 * q_value
        + p_value**4
        + 2 * p_value**3 * q_value**3
        - 7 * p_value**3 * q_value**2
        + 5 * p_value**3 * q_value
        - 2 * p_value**3
        + 2 * p_value**2 * q_value**4
        - 7 * p_value**2 * q_value**3
        + 12 * p_value**2 * q_value**2
        - 7 * p_value**2 * q_value
        + 2 * p_value**2
        - 2 * p_value * q_value**4
        + 5 * p_value * q_value**3
        - 7 * p_value * q_value**2
        + 2 * p_value * q_value
        + q_value**4
        - 2 * q_value**3
        + 2 * q_value**2
    )


def delta_expression(p_value: sp.Expr, q_value: sp.Expr) -> sp.Expr:
    return sp.expand(
        (p_value - q_value)
        * (p_value + q_value - 1)
        * (p_value**2 - p_value + 1)
        * (p_value**2 + 2 * p_value * q_value - 2 * p_value - q_value)
        * (2 * p_value * q_value - p_value + q_value**2 - 2 * q_value)
        * (
            2 * p_value * q_value**2
            - 2 * p_value * q_value
            - p_value
            - q_value**2
            - 2 * q_value
            + 2
        )
    )


SOURCE_SUFFIX = (
    "// Exact minimum-cardinality core found by the sealed selector scout.",
    "// Rank<=6 implies T3=Y1=X3=0; no selector converse is used.",
    "ideal I=Q6,H_T3,H_Y1,H_X3,z*B*Delta-1;",
    "timer=1;",
    "matrix T;",
    "ideal L=liftstd(I,T);",
    'print("LIFT_SECONDS");',
    "timer;",
    'print("BASIS_SIZE");',
    "size(L);",
    'print("BASIS_BEGIN");',
    "L;",
    'print("BASIS_END");',
    "int unit_column=0;",
    "int column;",
    "for (column=1;column<=size(L);column++)",
    "{",
    "  if ((L[column]!=0)&&(deg(L[column])==0)) { unit_column=column; }",
    "}",
    'print("UNIT_COLUMN");',
    "unit_column;",
    'if (unit_column==0) { print("ERROR_NO_UNIT_COLUMN"); quit; }',
    "poly unit_value=L[unit_column];",
    'print("UNIT_VALUE");',
    "unit_value;",
    'print("LIFT_MATRIX_CHECK_BEGIN");',
    "matrix(I)*T-matrix(L);",
    'print("LIFT_MATRIX_CHECK_END");',
    "poly identity=0;",
    "poly multiplier;",
    "int row;",
    "int nonzero_multipliers=0;",
    'print("NORMALIZED_MULTIPLIERS_BEGIN");',
    "for (row=1;row<=nrows(T);row++)",
    "{",
    "  multiplier=T[row,unit_column]/unit_value;",
    "  identity=identity+I[row]*multiplier;",
    "  if (multiplier!=0) { nonzero_multipliers=nonzero_multipliers+1; }",
    '  print("MULTIPLIER_ROW"); row;',
    '  print("MULTIPLIER_DEGREE_TERMS");',
    "  if (multiplier==0) { -1; } else { deg(multiplier); }",
    "  size(multiplier);",
    '  print("MULTIPLIER_POLYNOMIAL"); multiplier;',
    "}",
    'print("NORMALIZED_MULTIPLIERS_END");',
    'print("NONZERO_MULTIPLIERS");',
    "nonzero_multipliers;",
    'print("IDENTITY_SUM_MINUS_ONE");',
    "simplify(identity-1,2);",
    'print("CERTIFICATE_EXACT 1");',
    'print("RUN_COMPLETE 1");',
    "quit;",
)


def render_singular_source(payload: dict[str, Any]) -> str:
    algebra = payload["gaussian_quotient"]
    equations = payload["selected_minor_equations"]
    lines = [
        "// Juniper independent direct-matrix GLD101 d2 B-open audit v1",
        "// p=i; p=-i is coefficientwise conjugate.",
        "// Selected-minor ideal only; no rank converse or global claim.",
        "ring r=(0,i),(q,B,t,z),dp;",
        "minpoly=i^2+1;",
        "option(redSB);",
        f"poly Q6={algebra['q6_p_i']};",
        f"poly Delta={algebra['delta_mod_q6_p_i']};",
    ]
    lines.extend(
        f"poly H_{name}={equations[name]['singular_polynomial']};"
        for name in SELECTORS
    )
    lines.extend(SOURCE_SUFFIX)
    return "\n".join(lines) + "\n"


def check_scope(payload: dict[str, Any]) -> None:
    if payload.get("schema_version") != 1:
        raise PortableD2Error("unsupported certificate schema")
    if payload.get("certificate_id") != (
        "GLD101-A0-D2-B-open-T3-Y1-X3-portable-unit-leaf"
    ):
        raise PortableD2Error("certificate id mismatch")
    if payload.get("status") != "scoped_exact_selected_minor_unit_leaf":
        raise PortableD2Error("certificate status mismatch")
    if payload.get("global_conjecture") != "UNRESOLVED":
        raise PortableD2Error("global status must remain UNRESOLVED")
    scope = payload.get("mathematical_scope", {})
    if scope.get("factor") != "p^2+1=0" or scope.get("normalization") != "a=0":
        raise PortableD2Error("d2/a=0 scope drift")
    if scope.get("open") != "D(B*H2*Delta)":
        raise PortableD2Error("principal-open scope drift")
    if tuple(scope.get("actual_selected_minors", ())) != SELECTORS:
        raise PortableD2Error("six-selector scope drift")
    if tuple(scope.get("compact_unit_core", ())) != COMPACT_CORE:
        raise PortableD2Error("compact selector core drift")
    nonclaims = " ".join(scope.get("nonclaims", ())).lower()
    for phrase in ("no selector converse", "no claim on b=0", "no p8 theorem", "no global"):
        if phrase not in nonclaims:
            raise PortableD2Error(f"missing nonclaim: {phrase}")


def check_arithmetic(payload: dict[str, Any]) -> dict[str, Any]:
    algebra = payload["gaussian_quotient"]
    q6 = parse_singular_polynomial(algebra["q6_p_i"], (q,))
    delta = parse_singular_polynomial(algebra["delta_mod_q6_p_i"], (q,))
    expected_q6 = integral_gaussian_polynomial(
        sp.Poly(q6_expression(sp.I, q), q, extension=sp.I)
    )
    full_delta = sp.Poly(delta_expression(sp.I, q), q, extension=sp.I)
    expected_delta = integral_gaussian_polynomial(full_delta.rem(q6))
    if q6 != expected_q6:
        raise PortableD2Error("Q6 does not match the rational parent at p=i")
    if delta != expected_delta:
        raise PortableD2Error("Delta remainder does not match the rational parent")
    if q6.degree() != 4 or sp.gcd(q6, q6.diff()).degree() != 0:
        raise PortableD2Error("Q6 is not squarefree quartic on p=i")
    if sp.gcd(q6, delta).degree() != 0:
        raise PortableD2Error("Delta is not a unit modulo Q6")
    d2 = sp.Poly(p**2 + 1, p, domain=QQ)
    if not d2.is_irreducible:
        raise PortableD2Error("p^2+1 is not irreducible over QQ")
    h2_at_i = sp.expand(2 * sp.I**2 - 2 * sp.I + 1)
    real, imaginary = h2_at_i.as_real_imag()
    norm = sp.expand(real**2 + imaginary**2)
    if h2_at_i != -1 - 2 * sp.I or norm != 5:
        raise PortableD2Error("H2(i) or its Gaussian norm drifted")
    if algebra.get("h2_p_i") != "-1-2*i" or algebra.get("h2_gaussian_norm") != 5:
        raise PortableD2Error("tracked H2 gate mismatch")

    equations = payload["selected_minor_equations"]
    if set(equations) != set(SELECTORS):
        raise PortableD2Error("equation ordering drift")
    observed = {}
    for name in SELECTORS:
        record = equations[name]
        polynomial = parse_singular_polynomial(
            record["singular_polynomial"], (q, B, t)
        )
        digest = gaussian_polynomial_digest(polynomial)
        if digest != record["scaled_sha256"]:
            raise PortableD2Error(f"{name} scaled equation digest mismatch")
        degrees = {
            "q": int(polynomial.degree(q)),
            "B": int(polynomial.degree(B)),
            "t": int(polynomial.degree(t)),
        }
        if len(polynomial.terms()) != record["terms"] or degrees != record["degrees"]:
            raise PortableD2Error(f"{name} term/degree metadata mismatch")
        observed[name] = {"sha256": digest, "terms": len(polynomial.terms())}
    return {
        "q6_degree": int(q6.degree()),
        "q6_squarefree": True,
        "delta_unit_mod_q6": True,
        "h2_p_i": str(h2_at_i).replace("I", "i").replace(" ", ""),
        "h2_gaussian_norm": int(norm),
        "equations": observed,
    }


def verify(payload: dict[str, Any]) -> dict[str, Any]:
    check_scope(payload)
    arithmetic = check_arithmetic(payload)
    source = render_singular_source(payload)
    source_digest = sha256_bytes(source.encode("utf-8"))
    solver = payload["singular_unit_lift"]
    if source_digest != EXPECTED_SINGULAR_SOURCE_SHA256:
        raise PortableD2Error(f"Singular source digest mismatch: {source_digest}")
    if source_digest != solver.get("source_sha256"):
        raise PortableD2Error("certificate solver-source pin mismatch")
    if len(source.splitlines()) != solver.get("source_line_count"):
        raise PortableD2Error("Singular source line-count mismatch")
    for marker in solver.get("required_terminal_markers", ()):
        if marker not in source:
            raise PortableD2Error(f"missing solver marker: {marker}")
    return {
        "status": "exact_scoped_gld101_d2_bopen_portable_certificate_verified",
        "global_conjecture": "UNRESOLVED",
        "scope": "a=0,p^2+1=0,V(Q6),D(B*H2*Delta),selected necessary minors only",
        "actual_selected_minors": list(SELECTORS),
        "compact_unit_core": list(COMPACT_CORE),
        "p_i_branch": arithmetic,
        "p_minus_i_branch": "coefficientwise conjugate over rational parent equations",
        "singular_source_sha256": source_digest,
        "singular_source_line_count": len(source.splitlines()),
        "certificate_lf_sha256": EXPECTED_CERTIFICATE_LF_SHA256,
        "nonclaims_preserved": True,
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--emit-singular",
        type=Path,
        help="write the deterministic untracked Singular replay source",
    )
    args = parser.parse_args(argv)
    payload = load_certificate()
    report = verify(payload)
    if args.emit_singular is not None:
        target = args.emit_singular.resolve()
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("w", encoding="utf-8", newline="\n") as stream:
            stream.write(render_singular_source(payload))
        report["emitted_singular"] = str(target)
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
